/*
 * Which recording file holds which chapter.
 *
 * **Generated by scripts/build-audio-map.mjs, which asks the server rather
 * than reading its index**, because the index is wrong: it publishes
 * 22_Song_of_Soloman_01 and 25_Lamentations01 and both 404. Run `npm run
 * audio` to rebuild. Do not edit by hand.
 *
 * The tuple is [prefix, shape, recorded].
 *
 * `shape` is how the chapter number joins the prefix, and it is four
 * different answers because the recording is volunteer work rather than a
 * database export:
 *   under2  06_Joshua_01     most books
 *   under3  19_Psalm_001     Psalms alone
 *   bare1   25_Lam1          Lamentations alone, no separator, no padding
 *   whole   65_Jude          the one chapter books, which carry no number
 *
 * `recorded` is how many chapters the recording has, which is not always how
 * many this app has. The canon here is Catholic, so Esther runs to 16 and
 * Daniel to 14, and the recording stops at the Hebrew 10 and 12.
 *
 * Silent, and so absent from this map: 1 Maccabees, 1 Thessalonians, 2 Maccabees, 2 Thessalonians, Baruch, Judith, Sirach, Tobit, Wisdom.
 */
export type AudioShape = 'under2' | 'under3' | 'bare1' | 'whole';

/** [filename prefix, how the chapter number joins it, chapters recorded]. */
export const AUDIO_BOOKS: Record<string, readonly [string, AudioShape, number]> = {
  "1 Chronicles": ['13_1Chronicles', 'under2', 29],
  "1 Corinthians": ['46_1Cor', 'under2', 16],
  "1 John": ['62_1John', 'under2', 5],
  "1 Kings": ['11_1Kings', 'under2', 22],
  "1 Peter": ['60_1Peter', 'under2', 5],
  "1 Samuel": ['09_1Samuel', 'under2', 31],
  "1 Timothy": ['54_1Timothy', 'under2', 6],
  "2 Chronicles": ['14_2Chronicles', 'under2', 36],
  "2 Corinthians": ['47_2Cor', 'under2', 13],
  "2 John": ['63_2John', 'whole', 1],
  "2 Kings": ['12_2Kings', 'under2', 25],
  "2 Peter": ['61_2Peter', 'under2', 3],
  "2 Samuel": ['10_2Samuel', 'under2', 24],
  "2 Timothy": ['55_2Timothy', 'under2', 4],
  "3 John": ['64_3John', 'whole', 1],
  "Acts": ['44_Acts', 'under2', 28],
  "Amos": ['30_Amos', 'under2', 9],
  "Colossians": ['51_Colossians', 'under2', 4],
  "Daniel": ['27_Daniel', 'under2', 12],
  "Deuteronomy": ['05_Deuteronomy', 'under2', 34],
  "Ecclesiastes": ['21_Ecclesiastes', 'under2', 12],
  "Ephesians": ['49_Ephesians', 'under2', 6],
  "Esther": ['17_Esther', 'under2', 10],
  "Exodus": ['02_Exodus', 'under2', 40],
  "Ezekiel": ['26_Ezekiel', 'under2', 48],
  "Ezra": ['15_Ezra', 'under2', 10],
  "Galatians": ['48_Gal', 'under2', 6],
  "Genesis": ['01_Genesis', 'under2', 50],
  "Habakkuk": ['35_Habakkuk', 'under2', 3],
  "Haggai": ['37_Haggai', 'under2', 2],
  "Hebrews": ['58_Hebrews', 'under2', 13],
  "Hosea": ['28_Hosea', 'under2', 14],
  "Isaiah": ['23_Isaiah', 'under2', 66],
  "James": ['59_James', 'under2', 5],
  "Jeremiah": ['24_Jeremiah', 'under2', 52],
  "Job": ['18_Job', 'under2', 42],
  "Joel": ['29_Joel', 'under2', 3],
  "John": ['43_John', 'under2', 21],
  "Jonah": ['32_Jonah', 'under2', 4],
  "Joshua": ['06_Joshua', 'under2', 24],
  "Jude": ['65_Jude', 'whole', 1],
  "Judges": ['07_Judges', 'under2', 21],
  "Lamentations": ['25_Lam', 'bare1', 5],
  "Leviticus": ['03_Leviticus', 'under2', 27],
  "Luke": ['42_Luke', 'under2', 24],
  "Malachi": ['39_Malachi', 'under2', 4],
  "Mark": ['41_Mark', 'under2', 16],
  "Matthew": ['40_Matt', 'under2', 28],
  "Micah": ['33_Micah', 'under2', 7],
  "Nahum": ['34_Nahum', 'under2', 3],
  "Nehemiah": ['16_Nehemiah', 'under2', 13],
  "Numbers": ['04_Numbers', 'under2', 36],
  "Obadiah": ['31_Obadiah', 'whole', 1],
  "Philemon": ['57_Philemon', 'whole', 1],
  "Philippians": ['50_Philippians', 'under2', 4],
  "Proverbs": ['20_Prov', 'under2', 31],
  "Psalms": ['19_Psalm', 'under3', 150],
  "Revelation": ['66_Revelation', 'under2', 22],
  "Romans": ['45_Romans', 'under2', 16],
  "Ruth": ['08_Ruth', 'under2', 4],
  "Song of Songs": ['22_Song_of_Solomon', 'under2', 8],
  "Titus": ['56_Titus', 'under2', 3],
  "Zechariah": ['38_Zechariah', 'under2', 14],
  "Zephaniah": ['36_Zephaniah', 'under2', 3],
};
